/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sistema de Gestión
        </h1>


        <div className={styles.grid}>
          <a href="/menu-proyecto" className={styles.card}>
            <h2>Procesos &rarr;</h2>
            <p>Se lleva a cabo la gestión de todos los procesos utilizados por la empresa o equipo de desarrollo.</p>
          </a>

          <a href="/menu-proyecto" className={styles.card}>
            <h2>Proyectos &rarr;</h2>
            <p>Se realizan todas las gestiones relacionadas a las diferentes entidades del proyecto.</p>
          </a>

          <a
            href="/menu-scrum"
            className={styles.card}
          >
            <h2>Scrum &rarr;</h2>
            <p>Se realizan las gestiones necesarias para llevar a cabo la correcta implementación de la metodología SCRUM.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Evaluación &rarr;</h2>
            <p>
              Se lleva a cabo la implementación de la evaluación de la capacidad y calidad de los procesos de trabajo.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
