/* eslint-disable @next/next/no-html-link-for-pages */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function MenuScrum() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sistema de Gestión
        </h1>


        <div className={styles.grid}>
          <a
            href="/backlog"
            className={styles.card}>
            <h3>Backlog &rarr;</h3>
          </a>
          <a href="/sprint" className={styles.card}>
            <h3>Sprint &rarr;</h3>
          </a>
          <a href="/user-storie" className={styles.card}>
            <h3>User Storie &rarr;</h3>
          </a>
          <a
            href="/review"
            className={styles.card}>
            <h3>Review &rarr;</h3>
          </a>
        </div>
      </main>

    </div>
  )
}
